packages:
  - packages/*

catalog:
  '@jest/types': ^30.2.0
  '@testing-library/dom': ^10.4.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.0
  '@types/jest': ^30.0.0
  '@types/node': ^22.10.2
  '@types/react': 19.0.1
  '@types/react-dom': 19.0.2
  '@typescript-eslint/eslint-plugin': ^5.57.0
  '@typescript-eslint/parser': ^5.57.0
  '@vitejs/plugin-react': ^3.1.0
  cross-env: ^7.0.3
  eslint: ^8.37.0
  eslint-config-prettier: ^8.8.0
  eslint-plugin-prettier: ^4.2.1
  eslint-plugin-react: ^7.32.2
  expect-type: ^0.15.0
  immer: ^10.1.1
  inquirer: ^9.1.5
  jest: ^30.2.0
  jest-environment-jsdom: ^30.2.0
  nx: 15.9.0
  prettier: ^2.8.7
  react: 19.0.1
  react-dom: 19.0.1
  rimraf: ^4.4.1
  rxjs: ^7.8.0
  ts-jest: ^29.2.5
  ts-node: ^10.9.2
  tsc-alias: ^1.8.10
  typescript: ^5.9.3
  vite: ^4.2.1
  vite-plugin-dts: ^2.1.0
  vite-tsconfig-paths: ^4.0.7

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - nx
  - unrs-resolver
