name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: enhancedocs/setup-enhancedocs@0.1.3
        with:
          api-key: ${{ secrets.ENHANCEDOCS_API_KEY }}
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: yarn build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './docs/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: Build EnhanceDocs
        run: enhancedocs build docs
      - name: Publish EnhanceDocs
        run: enhancedocs push 6435f1864f5eaca6c03bf1d4
